
server:
  port: 8189
  servlet:
    context-path: /app
  error:
    include-message: always

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5433/finance_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  profiles:
    active: prod

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/master-changelog.yaml

management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    diskspace:
      enabled: true